FROM debian:latest

ENV TZ Asia/Shanghai

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources

RUN apt update && apt install -y \
        python3 python3-pip python3-venv pipx \
        vim exa curl wget zip unzip git man lsof procps \
        zsh zsh-autosuggestions zsh-syntax-highlighting \
        nginx

COPY . /tmp/
RUN tar -C /usr/local/bin/ -xf /tmp/starship-x86_64-unknown-linux-musl.tar.gz \
    && rm -rf /usr/local/go && tar -C /usr/local -xf /tmp/go1.21.1.linux-amd64.tar.gz \
    && useradd -m -s /usr/bin/zsh me \
    && passwd -d root

RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin \
    pipx install notebook -i https://mirror.sjtu.edu.cn/pypi/web/simple

USER me
WORKDIR /home/me

CMD [ "sh", "/tmp/run_jupyter" ]